import { v4 as uuidv4 } from 'uuid';
import type { Scene } from '@/types/editor';

export interface Template {
  id: string;
  name: string;
  description: string;
  category: 'minimal' | 'bold' | 'gradient' | 'showcase';
  preview: string; // CSS gradient for preview
  scenes: Scene[];
}

export const TEMPLATES: Template[] = [
  {
    id: 'clean-minimal',
    name: 'Clean Minimal',
    description: 'White background, subtle fade animations',
    category: 'minimal',
    preview: 'linear-gradient(135deg, #f5f5f5 0%, #e0e0e0 100%)',
    scenes: [
      {
        id: uuidv4(),
        name: 'Title',
        elements: [
          {
            id: uuidv4(),
            type: 'text',
            name: 'App Name',
            x: 560,
            y: 400,
            width: 800,
            height: 80,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            content: 'Your App Name',
            fontFamily: 'Inter, sans-serif',
            fontSize: 72,
            fontWeight: 700,
            color: '#1a1a2e',
            textAlign: 'center',
            lineHeight: 1.1,
            shadowColor: 'transparent',
            shadowBlur: 0,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            animation: { type: 'fade-in', duration: 30, delay: 5, easing: 'ease-out' },
          },
          {
            id: uuidv4(),
            type: 'text',
            name: 'Tagline',
            x: 560,
            y: 500,
            width: 800,
            height: 40,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            content: 'A beautiful tagline goes here',
            fontFamily: 'Inter, sans-serif',
            fontSize: 28,
            fontWeight: 400,
            color: '#666',
            textAlign: 'center',
            lineHeight: 1.4,
            shadowColor: 'transparent',
            shadowBlur: 0,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            animation: { type: 'fade-in', duration: 30, delay: 15, easing: 'ease-out' },
          },
        ],
        duration: 90,
        background: '#f8f8fa',
        transition: 'none',
      },
      {
        id: uuidv4(),
        name: 'Feature 1',
        elements: [
          {
            id: uuidv4(),
            type: 'device-frame',
            name: 'iPhone',
            x: 800,
            y: 215,
            width: 320,
            height: 650,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            deviceType: 'iphone-15-pro',
            color: '#1a1a2e',
            screenshotSrc: '',
            animation: { type: 'slide-up', duration: 25, delay: 5, easing: 'spring' },
          },
          {
            id: uuidv4(),
            type: 'text',
            name: 'Feature Text',
            x: 100,
            y: 450,
            width: 600,
            height: 60,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            content: 'Beautiful Interface',
            fontFamily: 'Inter, sans-serif',
            fontSize: 48,
            fontWeight: 600,
            color: '#1a1a2e',
            textAlign: 'left',
            lineHeight: 1.2,
            shadowColor: 'transparent',
            shadowBlur: 0,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            animation: { type: 'slide-right', duration: 20, delay: 10, easing: 'ease-out' },
          },
        ],
        duration: 90,
        background: '#f8f8fa',
        transition: 'fade',
      },
    ],
  },
  {
    id: 'bold-gradient',
    name: 'Bold Gradient',
    description: 'Vibrant gradients with bounce animations',
    category: 'bold',
    preview: 'linear-gradient(135deg, #6366f1 0%, #a855f7 50%, #ec4899 100%)',
    scenes: [
      {
        id: uuidv4(),
        name: 'Hero',
        elements: [
          {
            id: uuidv4(),
            type: 'text',
            name: 'Title',
            x: 460,
            y: 300,
            width: 1000,
            height: 120,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            content: 'NEXT LEVEL',
            fontFamily: 'Inter, sans-serif',
            fontSize: 96,
            fontWeight: 900,
            color: '#ffffff',
            textAlign: 'center',
            lineHeight: 1,
            shadowColor: 'rgba(0,0,0,0.3)',
            shadowBlur: 20,
            shadowOffsetX: 0,
            shadowOffsetY: 4,
            animation: { type: 'bounce', duration: 30, delay: 5, easing: 'spring' },
          },
          {
            id: uuidv4(),
            type: 'text',
            name: 'Subtitle',
            x: 460,
            y: 440,
            width: 1000,
            height: 50,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            content: 'Experience the difference',
            fontFamily: 'Inter, sans-serif',
            fontSize: 32,
            fontWeight: 400,
            color: 'rgba(255,255,255,0.9)',
            textAlign: 'center',
            lineHeight: 1.4,
            shadowColor: 'transparent',
            shadowBlur: 0,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            animation: { type: 'fade-in', duration: 20, delay: 20, easing: 'ease-out' },
          },
        ],
        duration: 90,
        background: '#4f46e5',
        transition: 'none',
      },
      {
        id: uuidv4(),
        name: 'Showcase',
        elements: [
          {
            id: uuidv4(),
            type: 'device-frame',
            name: 'Phone',
            x: 800,
            y: 215,
            width: 320,
            height: 650,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            deviceType: 'iphone-15-pro',
            color: '#0f0f23',
            screenshotSrc: '',
            animation: { type: 'zoom-in', duration: 25, delay: 5, easing: 'spring' },
          },
        ],
        duration: 90,
        background: '#7c3aed',
        transition: 'slide-left',
      },
    ],
  },
  {
    id: 'dark-showcase',
    name: 'Dark Showcase',
    description: 'Dark theme with sleek slide animations',
    category: 'showcase',
    preview: 'linear-gradient(135deg, #0f0f1a 0%, #1a1a3e 100%)',
    scenes: [
      {
        id: uuidv4(),
        name: 'Intro',
        elements: [
          {
            id: uuidv4(),
            type: 'text',
            name: 'Title',
            x: 460,
            y: 380,
            width: 1000,
            height: 100,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            content: 'Introducing',
            fontFamily: 'Inter, sans-serif',
            fontSize: 64,
            fontWeight: 300,
            color: '#ffffff',
            textAlign: 'center',
            lineHeight: 1.2,
            shadowColor: 'transparent',
            shadowBlur: 0,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            animation: { type: 'typewriter', duration: 40, delay: 5, easing: 'linear' },
          },
          {
            id: uuidv4(),
            type: 'text',
            name: 'App Name',
            x: 460,
            y: 470,
            width: 1000,
            height: 80,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            content: 'Your App',
            fontFamily: 'Inter, sans-serif',
            fontSize: 72,
            fontWeight: 700,
            color: '#8b5cf6',
            textAlign: 'center',
            lineHeight: 1.1,
            shadowColor: 'rgba(139,92,246,0.3)',
            shadowBlur: 30,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            animation: { type: 'zoom-in', duration: 20, delay: 30, easing: 'spring' },
          },
        ],
        duration: 90,
        background: '#0f0f1a',
        transition: 'none',
      },
    ],
  },
  {
    id: 'feature-callout',
    name: 'Feature Callout',
    description: 'Screenshot + feature text pairs with word reveal',
    category: 'showcase',
    preview: 'linear-gradient(135deg, #1e293b 0%, #334155 100%)',
    scenes: [
      {
        id: uuidv4(),
        name: 'Feature 1',
        elements: [
          {
            id: uuidv4(),
            type: 'device-frame',
            name: 'Phone',
            x: 150,
            y: 215,
            width: 320,
            height: 650,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            deviceType: 'iphone-15-pro',
            color: '#1e293b',
            screenshotSrc: '',
            animation: { type: 'slide-right', duration: 25, delay: 0, easing: 'spring' },
          },
          {
            id: uuidv4(),
            type: 'text',
            name: 'Feature Title',
            x: 550,
            y: 400,
            width: 800,
            height: 60,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            content: 'Smart and Intuitive',
            fontFamily: 'Inter, sans-serif',
            fontSize: 48,
            fontWeight: 700,
            color: '#f8fafc',
            textAlign: 'left',
            lineHeight: 1.2,
            shadowColor: 'transparent',
            shadowBlur: 0,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            animation: { type: 'word-reveal', duration: 40, delay: 10, easing: 'ease-out' },
          },
          {
            id: uuidv4(),
            type: 'text',
            name: 'Description',
            x: 550,
            y: 480,
            width: 800,
            height: 60,
            rotation: 0,
            opacity: 1,
            visible: true,
            locked: false,
            content: 'Designed to make your life easier',
            fontFamily: 'Inter, sans-serif',
            fontSize: 24,
            fontWeight: 400,
            color: '#94a3b8',
            textAlign: 'left',
            lineHeight: 1.4,
            shadowColor: 'transparent',
            shadowBlur: 0,
            shadowOffsetX: 0,
            shadowOffsetY: 0,
            animation: { type: 'fade-in', duration: 20, delay: 30, easing: 'ease-out' },
          },
        ],
        duration: 120,
        background: '#0f172a',
        transition: 'none',
      },
    ],
  },
];
